---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-claim
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
