---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-storage-new
  namespace: heimdall
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi